### ISSUE TITLE
IndexError: string index out of range

### ISSUE THREAD

**Issue by vlauciani** [INGV/qml2hypo71phs#1]
@actarus2971 quando eseguo la conversione con il file QML in allegato, ottengo questo errore:
```
root@6743293cdaaf:/opt#
root@6743293cdaaf:/opt# python3 /opt/qml2hypo71.py --qmlin /opt/input/20191019-110424__23297211__INGV-EVENT.qml
configparser loaded
Traceback (most recent call last):
  File "/opt/qml2hypo71.py", line 798, in <module>
    out_print=to_hypoinverse(pick_P,pick_S,amps,eid,version_name)
  File "/opt/qml2hypo71.py", line 300, in to_hypoinverse
    hi_line = v[0] + "x" + v[3] + pol + wei + v[8][2] + Ptime + hi_line[24:]
IndexError: string index out of range
root@6743293cdaaf:/opt#
root@6743293cdaaf:/opt#
```

[20191019-110424__23297211__INGV-EVENT.qml.zip](https://github.com/INGV/qml2hypo71phs/files/5925488/20191019-110424__23297211__INGV-EVENT.qml.zip)

**Comment by actarus2971** [comment]
É il solito problema che con il convertitore NLL già gestivo ... channelCode="" in qml. In nll metto un classico (per nll) interrogativo (?). Ora vedo come gestire l'assenza qui. Prima o poi però dovrebbe essere risolto in origine (o lo avete già fatto?).

**Comment by actarus2971** [comment]
Il bug dovrebbe essere fissato. Adesso se il chnl è vuoto, mette un singolo carattere vuoto dopo il peso e 3 dash "---" prima che network code.
